title: <p align="center"> Badari H </p>
logo: /assets/img/logo.jpg

description:
  <p align="center">
  <a>Resume</a> |
  <a>LinkedIn</a> |
  <a href="https://github.com/badarihp">GitHub</a>

  <br>
  I'm working on Data Science, Big Data, Spark, Machine learning & NLP related problems.
  <br>
  Also handing the Big Data from real-time Ad call data.
  <br>
  Worked with IBM Research at Big Data Analytics team.
  <br>
  Working in AdTech domain for 3 years.
  </p>

theme: jekyll-theme-minimal
